spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/sso?characterEncoding=utf8&useSSL=true
     username: root
#     password: Luo*zhen1234
     password: fenghaijun
     driver-class-name: com.mysql.jdbc.Driver
  cache:
    type: simple
#  #设置ftl模板文件路径
#  freemarker:
#    template-loader-path: classpath:/templates
#    #设置静态文件
#  mvc:
#    static-path-pattern: /static/**
mybatis:
  configuration:
    map-underscore-to-camel-case: true
